### ISSUE TITLE
writing images causes octave to crash

### ISSUE THREAD

**Issue by soneill93237** [its-pointless/its-pointless.github.io#45]
I have been unable to write images in octave because executing imwrite, print, or a number of other image-related functions causes the crash shown below. Does this have something to do with graphicsmagick?  I used imformats to produce the error below but it is identical to what I get when I try to write a png file with imwrite.

$ octave
octave: no graphical display found
octave: disabling GUI features
GNU Octave, version 5.1.0
Copyright (C) 2019 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "aarch64-unknown-linux-android".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> imformats
OMP: Error #15: Initializing libomp.a, but found libomp.a already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
fatal: caught signal Aborted -- stopping myself...
Aborted
$

**Comment by its-pointless** [comment]
tried recompiling and got it working again. Will upload shortly

**Comment by its-pointless** [comment]
Should be fixed.

**Comment by soneill93237** [comment]
I tried updating and upgrading and also purging and reinstalling octave and graphicsmagick but I still get the crash.  Is there something I need to do aside from this?
