### ISSUE TITLE
R packages install error

### ISSUE THREAD

**Issue by zcatav** [its-pointless/its-pointless.github.io#57]
Hi,
I use R in Termux. I newly solved upgrade problem with your assistance.
Now R installed and works. I'd installed r-cran-tidyverse. When I try to install data.table package in R, it works flawlessly. But when I try to install sqldf or RSQLite it throws following errors:

installing to /data/data/com.termux/files/usr/lib/R/library/00LOCK-RSQLite/00new/RSQLite/libs                                             ** R                                          ** inst                                       ** byte-compile and prepare package for lazy loading                                        Error in dyn.load(file, DLLpath = DLLpath, ...) :                                             unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/Rcpp/libs/Rcpp.so':                                           dlopen failed: library "libicuuc.so.65" not found                                         Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load            Execution halted                              ERROR: lazy loading failed for package ‘RSQLite’                                            * removing ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’                          * restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’                                                              The downloaded source packages are in                 ‘/data/data/com.termux/files/usr/tmp/RtmpSEo28q/downloaded_packages’                Updating HTML index of packages in '.Library' Making 'packages.html' ... done               Warning message:                              In install.packages("RSQLite") :                installation of package ‘RSQLite’ had non-zero exit status

Same things for sqldf package.

R version 3.6.3 andTermux is updated latest.
How can I install these packages?
Thanks in advance.

**Comment by its-pointless** [comment]
I will fic it tommorow. I have been busy.

**Comment by zcatav** [comment]
Thanks for your attention and these beautiful works.
Best regards.

**Comment by zcatav** [comment]
Did You have a chance to fix this problem.

**Comment by its-pointless** [comment]
should be fixed

**Comment by zcatav** [comment]
Hi,
R says error persist. 

installing to /data/data/com.termux/files/usr/lib/R/library/00LOCK-RSQLite/00new/RSQLite/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/bit/libs/bit.so':
  dlopen failed: library "libicuuc.so.65" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘RSQLite’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’

The downloaded source packages are in
        ‘/data/data/com.termux/files/usr/tmp/Rtmp2YwVff/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("RSQLite") :
  installation of package ‘RSQLite’ had non-zero exit status

**Comment by its-pointless** [comment]
I don't distribute the bit package. Reinstall the bit package using install.packages

**Comment by zcatav** [comment]
Sorry for disturbing again.
This is situation after installing bit package.
Unfortunately it doesn't work. 

testing if installed package keeps a record of temporary installation path
* DONE (bit)

installing to /data/data/com.termux/files/usr/lib/R/library/00LOCK-RSQLite/00new/RSQLite/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/bit64/libs/bit64.so':
  dlopen failed: library "libicuuc.so.65" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘RSQLite’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’

The downloaded source packages are in
        ‘/data/data/com.termux/files/usr/tmp/RtmpGfuwUL/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("RSQLite") :
  installation of package ‘RSQLite’ had non-zero exit status

**Comment by its-pointless** [comment]
what is output from this command 
`ldd /data/data/com.termux/files/usr/lib/R/library/bit64/libs/bit64.so ?`

**Comment by its-pointless** [comment]
what has likely happened is libicu was updated so the version library that was in that package namely libicuuc.so.65 no longer is installed. So some library either is linked against it in R/library/$PACKAGENAME/libs and it needs to be reinstalled. So either bit64.so or something else.

**Comment by zcatav** [comment]
It looks like;

>ldd /data/data/com.termux/files/usr/lib/R/library/bit64/libs/bit64.so

libandroid-support.so
libm.so
libgfortran.so.5
libopenblas.so
libandroid-glob.so
libiconv.so
liblzma.so.5
libjpeg.so
libpng16.so
libicuuc.so.65
libicudata.so.65
libcompiler_rt.so
libR.so
libc.so
libdl.so

**Comment by its-pointless** [comment]
rm   -rf /data/data/com.termux/files/usr/lib/R/library/bit64
Then install bit64

**Comment by zcatav** [comment]
Hi,
Thanks a lot, everythings all right now.
